<a href="https://colab.research.google.com/github/HPotty36/class2022Fall/blob/main/%EC%98%81%EC%96%B4%EC%9D%8C%EC%84%B1%ED%95%991111.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#파이썬크롤링 
#BeautifulSoup을 사용해서 정보 뽑아오기
#bookid는 홈페이지 주소의 숫자 - 이거를 입력해주고
#변수 = 내용의 형태
#for loop 다시 보기
#제공하는 사람은 서버 컴퓨터, 쓰는 사람은 클라이언트 컴퓨터
#request를 하는 과정이 있어야 하는데 리퀘스트할 때도 rest라고 request 보내는 방식이 표준
#nlp(자연어 처리)
#엑셀 타입은 무조건 행과 열로 - 엑셀처럼
#numpy - pandas와 비슷 (pandas는 숫자와 비슷?)
#numpy는 엑셀같이 생겼지만 숫자만 있는 거 - array
#numpy는 숫자 pandas
#pandas는 행과 열만, numpy는 3, 4차원 등 다 가능
#2차원으로 된 숫자는 행렬, 3,4차원 등은 tensor
#numpy


In [ ]:
#numpy - create nd arrays (~matrices)
import numpy as np #np는 numpy 패키지 안의 array 함수를 쓰려는 거
x = np.array([1,2,3]) #list와 같음 - list는 숫자를 가정하지 않기 때문에 array로 해야 진짜 숫자 보장됨
print(x)
print(type(x))
print(x.shape) #3개짜리 1D Array

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [ ]:
x = np.arange(0,10,2) #0에서 10까지 2만큼 띄어서, 10 포함 x
print(x)
print(type(x))
print(x.shape)

[0 2 4 6 8]
<class 'numpy.ndarray'>
(5,)


In [ ]:
x = np.linspace(0,10,6) #10도 포함해서 6개로 등분
print(x)
print(type(x))
print(x.shape)

[ 0.  2.  4.  6.  8. 10.]
<class 'numpy.ndarray'>
(6,)


In [ ]:
x = np.ones([2,2,3]) #2x2x3의 3차원
print(x)
print(type(x))
print(x.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>
(2, 2, 3)


In [ ]:
x = np.zeros([2,2,3])
print(x)
print(type(x))
print(x.shape)
x.reshape(3,2,2) #형태 바꾸기

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>
(2, 2, 3)


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
np.random.normal(0,1,[2,3,4])

array([[[-0.26704339,  0.3388553 ,  0.77396153, -0.32884716],
        [ 0.18402406,  1.89355115,  0.15009734, -1.70918309],
        [ 0.10200963,  1.33574464,  1.57192093,  0.29810281]],

       [[ 0.07836414, -0.00501222,  0.52732696,  0.12958504],
        [ 0.11015282,  1.81322957,  1.98622435,  0.01733307],
        [-0.76854232, -0.73966898, -0.08726279, -1.04986197]]])

In [ ]:
import matplotlib.pyplot as plt #matplotlib 안의 pyplot이라는 폴더 불러오기

In [ ]:
x = np.random.normal(0, 1, 100)
#y축 값 다 합치면 100 - 빈도니까


In [15]:
import pandas as pd
